# Generated by Django 3.1.2 on 2020-11-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkatdcu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpark',
            name='campus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus', to='parkatdcu.campus'),
        ),
    ]
